config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  resources :events do
    resources :tickets, only: [:new, :create]
  end

  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :tickets, dependent: :destroy
    has_one_attached :banner_image

    validates :name, presence: true
    validates :description, presence: true
    validates :status, inclusion: { in: %w[active inactive] }
    validates :max_allocation, numericality: { greater_than: 0 }

    # Active events are available for ticket registration
    scope :active, -> { where(status: 'active') }
    scope :inactive, -> { where(status: 'inactive') }

    def active?
        status == 'active'
    end

end

app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :event
    
    validates :name, presence: true
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :status, inclusion: { in: %w[pending confirmed] }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: "Event was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: "Event was successfully deleted."
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :description, :banner_image, :status, :max_allocation)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_event, only: [:new, :create]

  def new
    if @event.active?
      @ticket = @event.tickets.new
    else
      redirect_to events_path, alert: "This event is not active for registrations."
    end
  end

  def create
    if @event.active?
      @ticket = @event.tickets.new(ticket_params)
      available_tickets = @event.max_allocation - @event.tickets.count

      if available_tickets > 0
        if @ticket.save
          ConfirmTicketJob.perform_later(@ticket.id) #enqueue job
          redirect_to root_path, alert: 'Ticket registered successfully!'
        else
          render :new
        end
      else
        redirect_to root_path, alert: 'No More tickets available for this event!'
      end
    else
      redirect_to events_path, alert: 'This event is not active for registration.'
    end
  end

  private
  def set_event
    @event = Event.find(params[:event_id])
  end

  def ticket_params
    params.require(:ticket).permit(:name, :email, :status, :event_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/_form.html.erb
<%= form_with model: event, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :banner_image %>
    <%= form.file_field :banner_image %>
  </div>

  <div>
    <%= form.label :status %>
    <%= form.select :status, ['active', 'inactive'], selected: @event.status || 'inactive' %>
  </div>

  <div>
    <%= form.label :max_allocation %>
    <%= form.number_field :max_allocation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render "form", event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Upcoming Events</h1>

<%= link_to 'New Event', new_event_path %>

<% @events.each do |event| %>
  <div>
    <h2><%= event.name %> (Available tickets: <%= event.max_allocation - event.tickets.count %>)</h2>
    <p><%= event.description %></p>
    <%= image_tag event.banner_image, :width => "25%" if event.banner_image.present? %>
    <p>Status: <%= event.status.capitalize %></p>
    <p>Max Allocation: <%= event.max_allocation %></p>
    <%= link_to 'Show', event_path(event) %> |
    <%= link_to 'Edit', edit_event_path(event) %> |
    <%= link_to 'Delete', event_path(event), method: :delete, data: { confirm: 'Are you sure you want to delete this event?' } %> |
    <%= link_to 'Register', new_event_ticket_path(event) %>
  </div>
<% end %>

app/views/events/new.html.erb
<h1>Edit Event</h1>

<%= render "form", event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<p><%= @event.description %></p>
<%= image_tag @event.banner_image, :width => "25%" if @event.banner_image.present? %>
<p>Status: <%= @event.status.capitalize %></p>
<p>Max Allocation: <%= @event.max_allocation %></p>

<hr>
<h2>List registered tickets</h2>
<ul>
    <% @event.tickets.each do |ticket| %>
        <li><%= ticket.name %></li>
    <% end %>
</ul>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Delete', event_path(@event), method: :delete, data: { confirm: 'Are you sure you want to delete this event?' } %> |
<%= link_to 'Back to Events', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ticketing Systems" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/new.html.erb
<h1>Register for a Ticket for <%= @event.name %></h1>

<%= form_with model: [@event, @ticket], local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.hidden_field :status, :value => 'pending' %>
  </div>



  <div>
    <%= form.submit 'Register' %>
  </div>
<% end %>